---
title: WPDesign
author: Anton Toni Agung
email: vdrive6@gmail.com
description: WPDesign adalah penyedia jasa pembuatan web WordPress, setup VPS, migrasi
  WordPress.
baseurl: "/"
url: wp-designs.studio
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
